<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql" Version="13.3.2" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.23.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.28.0" />
    <PackageReference Include="Google.Cloud.Storage.V1" Version="4.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Npgsql.OpenTelemetry" Version="10.0.2" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.3" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.11" />
    <PackageReference Include="System.Linq.Async" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AgeDigitalTwins\AgeDigitalTwins.csproj" />
    <ProjectReference Include="..\AgeDigitalTwins.ServiceDefaults\AgeDigitalTwins.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
