name: Update Docs Repository

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: "docs-update"
  cancel-in-progress: false

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: source

      - name: Checkout docs repository
        uses: actions/checkout@v4
        with:
          repository: konnektr-io/docs
          token: ${{ secrets.GITHUB_TOKEN }}
          path: docs-repo

      - name: Remove existing graph docs
        run: |
          if [ -d "docs-repo/content/docs/graph" ]; then
            rm -rf docs-repo/content/docs/graph
          fi

      - name: Copy docs to target repository
        run: |
          mkdir -p docs-repo/content/docs/graph
          cp -r source/docs/* docs-repo/content/docs/graph/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          path: docs-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update Konnektr Graph documentation"
          title: "Update Konnektr Graph documentation"
          body: |
            This PR updates the Konnektr Graph documentation with the latest changes from the pg-age-digitaltwins repository.
            
            **Changes:**
            - Updated documentation content in `/content/docs/graph/`
            
            **Source:** ${{ github.repository }}@${{ github.sha }}
          branch: update-graph-docs-${{ github.run_number }}
          delete-branch: true
