name: Run Integration Tests

on:
  workflow_dispatch:
    inputs:
      test_project:
        description: "Select the test project to run"
        required: true
        default: "All"
        type: choice
        options:
          - All
          - AgeDigitalTwins.Test
          - AgeDigitalTwins.ApiService.Test
          - AgeDigitalTwins.Events.Test
          - AgeDigitalTwins.MCPServerSSE.Test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ghcr.io/konnektr-io/age:16-bookworm-4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
        volumes:
          - ${{ github.workspace }}/src/data/init.sql:/docker-entrypoint-initdb.d/init.sql
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Set wal_level to logical
        env:
          PGPASSWORD: "app"
        run: psql -h localhost -U app -c "ALTER SYSTEM SET wal_level = 'logical';"

      - name: Create Database
        env:
          PGPASSWORD: "app"
        run: psql -h localhost -U app -c 'CREATE DATABASE "app";'

      - name: Restart Postgres
        env:
          PGPASSWORD: "postgres"
        run: docker restart $(docker ps -q --filter "ancestor=age:16-bookworm-4")

      - name: Print Services
        run: service --status-all

      - name: Test
        run: |
          if [ "${{ github.event.inputs.test_project }}" == "All" ]; then
            dotnet test './src' --logger 'GitHubActions' --verbosity detailed
          else
            dotnet test './src/${{ github.event.inputs.test_project }}' --logger 'GitHubActions' --verbosity detailed
          fi
