name: Run Integration Tests

on:
  workflow_dispatch:
    inputs:
      test_project:
        description: "Select the test project to run"
        required: true
        default: "All"
        type: choice
        options:
          - All
          - AgeDigitalTwins.Test
          - AgeDigitalTwins.ApiService.Test
          - AgeDigitalTwins.Events.Test
          - AgeDigitalTwins.MCPServerSSE.Test

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: ghcr.io/konnektr-io/age:16-bookworm-4
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: app
          POSTGRES_DB: app
        volumes:
          - ${{ github.workspace }}/src/data/init.sql:/docker-entrypoint-initdb.d/init.sql
        options: >-
          --health-cmd "pg_isready -U app -d app"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20
          --max-connections=100
          --wal_level=logical

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Test
        run: |
          if [ "${{ github.event.inputs.test_project }}" == "All" ]; then
            dotnet test './src' --logger 'GitHubActions' --verbosity detailed
          else
            dotnet test './src/${{ github.event.inputs.test_project }}' --logger 'GitHubActions' --verbosity detailed
          fi
