name: Run Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Run Unit Tests
        run: dotnet test './src' --filter 'Category!=Integration' --logger 'GitHubActions;verbosity=detailed'
